### ISSUE TITLE
Now in OpenBSD

### ISSUE THREAD

**Issue by gonzalo-** [mrusme/planor#2]
Hi!

I [ported Planor some days ago](https://cvsweb.openbsd.org/ports/sysutils/planor/) to OpenBSD and it is available on -current already, and it will be in the next releases by ,,pkg_add planor''.

Thanks!

**Comment by mrusme** [comment]
Hey @gonzalo-, that's great, thank you! Will test this and add an info to the README. Do you mind if I link your GitHub profile there as maintainer?

**Comment by gonzalo-** [comment]
Sure, go ahead, no problem I will do my best to keep it up-to-date :)
